language: ruby
rvm:
  - 2.1.1

cache: bundler
script:
  - bundle exec jekyll build
  - bundle exec ./validate.rb

after_success:
  - 'curl -s http://google.com/ping\?sitemap=http:%3A%2F%2Fblog.sigurdhsson.org%2Fsitemap.xml > /dev/null'
