source 'https://rubygems.org'
gem 'github-pages', '>= 192'
gem 'nokogiri', '>= 1.8.2'
gem 'html5_validator'
gem 'w3c_validators', '>= 1.3.2'
gem 'colorize'
gem 'html-proofer', '>= 3.7.2'
gem 'open_uri_redirections'
