source 'https://rubygems.org'
gem 'github-pages', '>= 181'
gem 'nokogiri', '>= 1.8.5'
gem 'html5_validator'
gem 'w3c_validators', '>= 1.3.3'
gem 'colorize'
gem 'html-proofer', '>= 3.8.0'
gem 'open_uri_redirections'
